package message;
public enum MessageType {
    CS_REQUEST, 
    CS_RESPONSE,
    CS_EXIT,
    CENTRAL_CLIENT_HANDSHAKE,
    CENTRAL_SERVER_HANDSHAKE,
    CLIENT_HANDSHAKE,
    SERVER_HANDSHAKE,
    CLIENT_INFO,
    SERVER_CONN,
    USER_INPUT
}
